# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Calendr' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Calendr
  pod 'SnapKit', '~> 5.6.0'

  # Authentication
  pod 'FirebaseFirestore'
  pod 'KeychainSwift', '~> 20.0'
  
  # Databinding
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'

  target 'CalendrTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CalendrUITests' do
    # Pods for testing
  end

end
